# Catppuccin Mocha — https://github.com/catppuccin/fuzzel
[colors]
background=1e1e2eff
text=cdd6f4ff
prompt=bac2deff
placeholder=9399b2ff
input=cdd6f4ff
match=cba6f7ff
selection=45475aff
selection-text=cdd6f4ff
selection-match=cba6f7ff
counter=9399b2ff
border=cba6f7ff
