# Dracula — https://github.com/dracula/fuzzel
[colors]
background=282a36ff
text=f8f8f2ff
prompt=bd93f9ff
placeholder=6272a4ff
input=f8f8f2ff
match=ff79c6ff
selection=44475aff
selection-text=f8f8f2ff
selection-match=ff79c6ff
counter=6272a4ff
border=bd93f9ff
