# Gruvbox Dark — https://github.com/morhetz/gruvbox
[colors]
background=282828ff
text=ebdbb2ff
prompt=a89984ff
placeholder=928374ff
input=ebdbb2ff
match=fabd2fff
selection=504945ff
selection-text=ebdbb2ff
selection-match=fabd2fff
counter=928374ff
border=fabd2fff
