# Nord — https://www.nordtheme.com
[colors]
background=2e3440ff
text=d8dee9ff
prompt=81a1c1ff
placeholder=4c566aff
input=eceff4ff
match=88c0d0ff
selection=434c5eff
selection-text=eceff4ff
selection-match=88c0d0ff
counter=4c566aff
border=88c0d0ff
