# Rose Pine (main) — https://rosepinetheme.com
[colors]
background=191724f0
text=e0def4ff
prompt=908caaff
placeholder=6e6a86ff
input=e0def4ff
match=ebbcbaff
selection=26233aff
selection-text=e0def4ff
selection-match=ebbcbaff
counter=6e6a86ff
border=9ccfd8ff
