preload = /home/raja/Documents/wallpaper/Space-Nebula.png
wallpaper = eDP-1, /home/raja/Documents/wallpaper/Space-Nebula.png
wallpaper = DP-1, /home/raja/Documents/wallpaper/Space-Nebula.png

splash = false
